### ISSUE TITLE
Use environment variables in the settings file

### ISSUE THREAD

**Issue by tim-schilling** [differentreality/supplies_tracker#72]
You absolutely need to change your secret key ([some reasons why](https://security.stackexchange.com/a/61911)) and then switch it with something similar to:

```python
SECRET_KEY = os.environ.get('SECRET_KEY')
```

Do the same for your google API key.

**Comment by angeanto** [comment]
@tim-schilling There's a default way to do this or just change the key in everything i want ?

**Comment by tim-schilling** [comment]
To get a new key:

```
python manage.py shell -c 'from django.core.management import utils; print(utils.get_random_secret_key())'
```

**Comment by angeanto** [comment]
i got a key and passed it to pythonanywhere although i changed it to secret here in github . #74 
Is this what you suggested ?

**Comment by robertpro** [comment]
You have to save a environment variable like this in your linux server:

```bash
export SECRET_KEY="S3CR3T"
```

And in your settings file load that environment variable like this:

```python
import os
SECRET_KEY = os.environ.get('SECRET_KEY')
```

There is a way in [PythonAnywhere](https://help.pythonanywhere.com/pages/environment-variables-for-web-apps/) to set an environment variable.

**Comment by angeanto** [comment]
I think it works  the way i did it @robertpro

**Comment by robertpro** [comment]
It works, but it is not correct :( @angeanto
